### ISSUE TITLE
Set the default branch of rendered repository to "main"

### ISSUE THREAD

**Issue by mdpiper** [csdms/babelizer#58]
This follows the current GitHub convention. The current default branch name in the rendered repository is "master".

**Comment by mdpiper** [comment]
We could make this an option for the user; e.g., `github_branch` in the info section:
```toml
[info]
github_username = "pymt-lab"
github_branch = "main"
package_author = "csdms"
package_author_email = "csdms@colorado.edu"
package_license = "MIT"
summary = "PyMT plugin for hydrotrend"
```
